name: "deploy"
on:
  push:
    branches:
      - gh-pages
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build
      - run: |
          git config user.name "Vincent Le Badezet"
          git config user.email v.lebadezet@untemps.net
          git add .
          git commit -m "chore(release): Deploy Github pages [skip ci]"
          git push
